[package]
name = "trait-bounds"
version = "0.1.0"
edition = "2024"
description = "Trait bounds primitives using generic_const_exprs"
license = "MIT OR Apache-2.0"
repository = "https://codeberg.org/funsafemath/trait-bounds"

[dependencies]

[lints.clippy]
pedantic.level = "warn"
nursery.level = "warn"
